services:
  db:
    image: postgres:16
    container_name: translation-app-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: root
      POSTGRES_DB: translation_db
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d translation_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres:
    name: translation-app-postgres