service: translation-app
# Name of the container image.
image: ghcr.io/andrianarivo/translation-app

# Deploy to these servers.
servers:
  - 134.209.238.100

# Credentials for your image host.
registry:
  server: ghcr.io
  username: [KAMAL_REGISTRY_USERNAME]
  password: [KAMAL_REGISTRY_PASSWORD]

builder:
  multiarch: false
  context: ./backend
  dockerfile: ./backend/Dockerfile

healthcheck:
  path: /
  port: 8000

# Configuration simplifiée pour exposer directement le port 3002
traefik:
  args:
    entryPoints.web.address: :3002
  options:
    publish: ['3002:3002']

# Inject ENV variables into containers (secrets come from .env).
env:
  clear:
    DB_HOST: localhost
    DB_PORT: 5432
  secret:
    - FRONTEND_URL
    - NODE_ENV
    - DATABASE_URL
    - SERVER_ADDR

# Use a different ssh user than root
ssh:
  user: root

# Use accessory services (secrets come from .env).
accessories:
  db:
    image: postgres:16
    host: localhost
    port: 5433:5432
    env:
      secret: [POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB]
    directories:
      - translation-db-data:/var/lib/postgresql/data